### ISSUE TITLE
Request for a project database

### ISSUE THREAD

**Issue by mugishahub1994** [agbilotia1998/PHP-MySQL-Event-Management-System#1]
Hello am Didos, can you plz provide a database for this wonderful project?
my email is didosrukundo@yahoo.com
thx

**Comment by iNezerr** [comment]
Kindly provide the database
bonuzx1@gmail.com
Thanks

**Comment by kent-vypes** [comment]
May I please have the database for this project thanks 
kvipey791@gmail.com

**Comment by manjunathhegdebalgar** [comment]
can you please send the database file to hmanjub@gmail.com ? thanks

**Comment by agbilotia1998** [comment]
Sorry for the delay in reply, I just made this project for understanding the basics of PHP with mySQL so didn't add anything :sweat_smile:. I've added the database file `db_init.sql` and the `.env.example` file for all the environment variables. Feel free to ping in case you face any issue.
