### ISSUE TITLE
mysql database sql file? 

### ISSUE THREAD

**Issue by Pyksa** [agbilotia1998/PHP-MySQL-Event-Management-System#3]
I can not find it anywhere..

**Comment by ljcamren** [comment]
yah.... wheres the sql file?

**Comment by agbilotia1998** [comment]
Sorry for the delay in reply, I just made this project for understanding the basics of PHP so didn't add anything :sweat_smile:. Added the database file `db_init.sql` and the `.env.example` file for all the environment variables.
